# Generated by Django 2.0 on 2019-02-15 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0051_auto_20190210_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='addlecture',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 15, 12, 2, 28, 466503)),
        ),
        migrations.AddField(
            model_name='activityrequest',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.AddLecture'),
        ),
        migrations.AddField(
            model_name='activityrequest',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.Expert'),
        ),
        migrations.AddField(
            model_name='activityrequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.Student'),
        ),
    ]
